calendar/calen/urls.py
from django.urls import path

from . import views

app_name = ("calen")

urlpatterns = [
    path("", views.index, name="index"),
    path("kolo", views.kolo, name="kolo"),
    path("udalosti", views.udalosti, name="udalosti"),
    path("detail/<int:udalost_id>", views.detail, name="detail"),
    path("register", views.RegisterView.as_view(), name="register"),
    path("logout", views.log_out, name="logout"),
    path("login", views.log_in, name="login"),
]

calendar/calendarApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("calen.urls")),
]

calendar/calen/models.py
from datetime import datetime

from django.db import models

# Create your models here.
class Udalost(models.Model):
    jmeno = models.CharField(max_length=150, null=False)
    popis = models.TextField(max_length=500, null=True)
    zacatek = models.DateTimeField(default=datetime.now())
    konec = models.DateTimeField(default=datetime.now())
    jen_zacatek = models.BooleanField(default=False)
    celodenni = models.BooleanField(default=True)
    def __str__(self):
        return str(self.jmeno) + ": ("+ str(self.popis) + ")"

class Ukol(models.Model):
    jmeno = models.CharField(max_length=150, null=False)
    popis = models.TextField(max_length=500, null=True)
    deadline = models.DateTimeField(default=datetime.now())
    splneno = models.BooleanField(default=False)
    udalost = models.ForeignKey(Udalost, on_delete=models.CASCADE, null=False)

    def __str__(self):
        return str(self.udalost.jmeno) + " -> " + self.jmeno

calendar/calen/views.py
import django.contrib.auth.forms as forms
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from django.views import generic
from django.urls import reverse_lazy

def index(request):
    a = 5
    b = a**2
    c = 4
    p = [13, "Liška", 999.99]
    return render(request, "calen/index.html", {"a": a, "mocnina": b, "kriterium": c, "pole":p})

def kolo(request):
    return HttpResponse("Stránka s koly!")


def udalosti(request):
    ud = Udalost.objects.all()
    return render(request, "calen/udalosti.html", {"udalosti": ud})

@login_required
def detail(request, udalost_id):
    ud = get_object_or_404(Udalost, pk=udalost_id)
    return render(request, "calen/detail_udalosti.html", {"udalost": ud})

class RegisterView(generic.CreateView):
    template_name = "calen/register.html"
    success_url = reverse_lazy("calen:udalosti")
    form_class = forms.UserCreationForm

def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy("calen:udalosti"))

def log_in(request):
    form = forms.AuthenticationForm(request)
    msg = ""
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse_lazy("calen:udalosti"))
    elif request.method == "POST":
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            msg = "ŠPATNÉ JMÉNO NEBO HESLO"
            return render(request, template_name="calen/login.html", context={'form': form, 'msg': msg})
        else:
            login(request, user)
            return HttpResponseRedirect(reverse_lazy("calen:udalosti"))
    else:
        return render(request, 'calen/login.html', {'form':form, 'msg':msg})

calendar/calen/templates/calen/base.html
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Udalosti{% endblock %}</title>
</head>
<body>
    <h1>Naše super aplikace!!</h1>
    {% block content %}

    {% endblock %}
    <footer>
        Vytvořeno v AIT 2025
    </footer>
</body>
</html>

calendar/calen/templates/calen/detail_udalosti.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<h1>Detail události: {{ udalost.jmeno }}</h1>
    <br>Začátek: {{ udalost.zacatek }}
    {% if not udalost.jen_zacatek %}
        <br>Konec: {{ udalost.konec }}
    {% endif %}
    <br>Popis: {{ udalost.popis }}
    <br>Celodenní: {{ udalost.celodenni }}
<H3>Úkoly:</H3>
{% for t in udalost.ukol_set.all %}
    {{ t.jmeno }}: deadline: {{ t.deadline }}<br>
{% endfor %}
</body>
</html>

calendar/calen/templates/calen/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
<h1>Moje super stánka</h1><br>
<b>ÁČKO: {{ a }}</b><br>
<b>MOCNINA: {{ mocnina }}</b><br>
<b>Kritérium: {{ kriterium }}</b><br>
{% if kriterium > 5 %}
    <i>Je to větší než 5!</i>
{% else %}
    <i>MENŠÍ!</i>
{% endif %}
<br>
<hr>
{% for i in pole %}
    -- {{ i }} <br>
{% endfor %}

<a href="{% url "calen:kolo" %}">Stránka s koly</a>

</body>
</html>

calendar/calen/templates/calen/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>{{ msg }}</h2>
<form action="{% url 'calen:login' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Přihlásit">
</form>

</body>
</html>

calendar/calen/templates/calen/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registrace</title>
</head>
<body>
    <form action="{% url 'calen:register'  %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Vytvořit účet">
    </form>
</body>
</html>

calendar/calen/templates/calen/udalosti.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Události</title>
</head>
<body>
    <h1>Moje události</h1>
    <h2>{{ user }}</h2>
    <a href="{% url 'calen:logout' %}"> Odhlásit se</a>
    <a href="{% url 'calen:login' %}"> Přihlásit se</a>
    {% for u in udalosti %}
        <br><a href="{% url "calen:detail" u.id %}"> {{ u }}</a>
    {% endfor %}
</body>
</html>